AllCops:
  Exclude:
    - 'test/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'ngw32/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false