# -*- ruby -*-

require 'date'
require 'rubygems'
require 'hoe'
require 'pp'

Hoe.spec 'ruby-pg' do
  developer 'Michael Granger', 'ged@FaerieMUD.org'
  dependency 'pg', '~> 0'
  spec_extras[:date] = Date.parse('2008/01/30')

  line = '-' * 75
  msg = paragraphs_of('README.txt', 3..-1)
  msg.unshift(line)
  msg.push(line)

  spec_extras[:post_install_message] = "#{msg.join("\n\n")}\n"
end

# vim: syntax=ruby
